import Head from "next/head";
import { Button } from "@telegraph/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Telegraph Style Engine Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button size="1" color="blue">
          Click me
        </Button>
        <Button size="2" color="accent">
          Click me
        </Button>
      </div>
    </>
  );
}
