import Head from "next/head";
import { Button } from "@telegraph/button";
import { Heading, Text, Code } from "@telegraph/typography";
import { Stack } from "@telegraph/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Telegraph Style Engine Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack direction="column">
        <Stack
          direction="column"
          gap="2"
          border="px"
          m="8"
          p="6"
          rounded="4"
          style={{
            maxWidth: "800px",
          }}
        >
          <Heading as="h1" size="5">
            Telegraph style engine example
          </Heading>
          <Text as="p" size="2" weight="regular" color="gray">
            The{" "}
            <Code as="code" color="gray">
              @telegraph/style-engine
            </Code>{" "}
            PostCSS plugin makes styling simpler. Just add{" "}
            <Code as="code" color="gray">
              @telegraph
            </Code>{" "}
            rules to your{" "}
            <Code as="code" color="gray">
              globals.css
            </Code>{" "}
            file to automatically include styles from any Telegraph package. No
            need to manually import individual stylesheets - the plugin handles
            it all for you.
          </Text>
          <Heading as="h2" size="2" mt="4">
            PostCSS config example
          </Heading>
          <Code as="code" color="gray" p="4">
            {`
            {
              "plugins": ["@telegraph/style-engine/postcss"]
            }
            `}
          </Code>
          <Heading as="h2" size="2">
            CSS file example
          </Heading>
          <Code as="code" color="gray" p="4">
            @telegraph tokens; // Include all color tokens for light and dark
            appearance
            <br />
            @telegraph tokens-light; // Include only light color tokens
            <br />
            @telegraph tokens-dark; // Include only dark color tokens
            <br />
            @telegraph components; // Include styles for all telegraph
            components installed in your project
          </Code>
        </Stack>
        <Stack direction="column" gap="2" px="8" py="4">
          <Heading as="h2" size="3">
            Example components
          </Heading>
          <Stack direction="row" gap="2">
            <Text as="span" size="2" weight="regular" color="gray">
              Text
            </Text>
            <Text as="span" size="3" weight="regular" color="blue">
              Text
            </Text>
            <Text as="span" size="4" weight="regular" color="green">
              Text
            </Text>
          </Stack>
          <Stack direction="row" gap="2">
            <Button size="1" color="blue">
              Button
            </Button>
            <Button size="2" color="accent">
              Button
            </Button>
            <Button size="3" color="green">
              Button
            </Button>
          </Stack>
        </Stack>
      </Stack>
    </>
  );
}
