version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    ignore:
      # vite >7 breaks storybook
      - dependency-name: "vite"
        versions: [">=7.0.0"]
