name: Check Package Sizes

on:
  pull_request:

concurrency:
  group: check-package-sizes-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-package-sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Current Branch
        run: yarn build:packages
      - name: Get Current Package Sizes
        uses: ./.github/actions/check-package-sizes-action
        id: current-package-sizes
      # Adds this in once merged to main
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Current Branch
        run: yarn build:packages
      - name: Get Main Package Sizes
        uses: ./.github/actions/check-package-sizes-action
        id: main-package-sizes
      - name: Compare Package Sizes
        uses: ./.github/actions/compare-package-sizes-action
        with:
          current-package-sizes: ${{ steps.current-package-sizes.outputs.package-sizes }}
          main-package-sizes: ${{ steps.main-package-sizes.outputs.package-sizes }}
        id: compare-package-sizes
