name: Check Package Sizes

on:
  pull_request:

concurrency:
  group: check-package-sizes-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-package-sizes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "yarn"
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Current Branch
        run: yarn build:packages
      - name: Get Current Package Sizes
        uses: ./.github/actions/check-package-sizes-action
        id: current-package-sizes
      # Adds this in once merged to main
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     ref: main
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Current Branch
        run: yarn build:packages
      - name: Get Main Package Sizes
        uses: ./.github/actions/check-package-sizes-action
        id: main-package-sizes
      - name: Compare Package Sizes
        uses: ./.github/actions/compare-package-sizes-action
        with:
          current-package-sizes: ${{ steps.current-package-sizes.outputs.package-sizes }}
          previous-package-sizes: ${{ steps.main-package-sizes.outputs.package-sizes }}
        id: compare-package-sizes
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: #### Package size differences
      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.compare-package-sizes.outputs.pr-comment }}
      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.compare-package-sizes.outputs.pr-comment }}
          edit-mode: replace
