name: CI

on:
  pull_request:
  push:
    branches:
      - changeset-release/main
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/setup-files.yml

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  format:
    needs: setup
    uses: ./.github/workflows/format.yml

  test:
    needs: setup
    uses: ./.github/workflows/unit-test-packages.yml
