name: Code Checks

on:
  merge_group:
  pull_request:

concurrency:
  group: code-checks-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    uses: ./.github/workflows/install-dependencies.yml
  build-packages:
    name: Build Packages
    needs: [install-dependencies]
    uses: ./.github/workflows/build-packages.yml
  format:
    name: Check Project Formatting
    needs: [install-dependencies, build-packages]
    uses: ./.github/workflows/format.yml
  lint:
    name: Lint Project
    needs: [install-dependencies, build-packages]
    uses: ./.github/workflows/lint.yml
  unit-test-packages:
    name: Unit Test Packages
    needs: [install-dependencies, build-packages]
    uses: ./.github/workflows/unit-test-packages.yml
