name: Commitlint PR

concurrency:
  group: commitlint-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install Commitlint CLI
         run: yarn add @commitlint/config-conventional --frozen-lockfile
       - name: Run Commitlint on PR Title
         uses: JulienKode/pull-request-name-linter-action@v0.1.2
