name: Commitlint PR

on:
  pull_request:

concurrency:
  group: commitlint-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint-pr:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install Commitlint CLI
         run: yarn add @commitlint/config-conventional --frozen-lockfile
       - name: Run Commitlint on PR Title
         uses: JulienKode/pull-request-name-linter-action@v0.1.2
