name: Commitlint PR

on:
  merge_group:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

concurrency:
  group: commitlint-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commitlint on PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
