name: Commitlint PR

concurrency:
  group: commitlint-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install Commitlint CLI
         uses: yarn add @commitlint/config-conventional --frozen-lockfile
       - name: Run Commitlint on PR Title
         uses: amannn/action-semantic-pull-request@v1.2.0
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
