name: Commitlint PR

on:
  pull_request:

concurrency:
  group: commitlint-pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint-pr:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
          node-version-file: "package.json"
          cache: 'yarn'
       - name: Install Commitlint CLI
         run: yarn
       - name: Run Commitlint on PR Title
         uses: JulienKode/pull-request-name-linter-action@v0.1.2
         with:
           configuration-path: ./commitlint.config.js
