name: Check Project Formatting

on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: format-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   check-project-formatting:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
       - name: Setup Node
         uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
         with:
          node-version-file: "package.json"
          cache: 'yarn'
       - name: Install Dependencies
         run: yarn --immutable
       - name: Run Format Check
         run: yarn format:check
