name: Lint Project

on:
  workflow_call:

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   lint-project:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
          node-version-file: "package.json"
          cache: 'yarn'
       - name: Cache Build
         id: build-packages-cache
         uses: actions/cache@v3
         with:
           path: |
            **/dist
           key: build:packages-${{ hashFiles('packages') }}
       - name: Install Dependencies
         run: yarn --immutable
       - name: Build Packages
         if: steps.build-packages-cache.outputs.cache-hit != 'true'
         run: yarn build:packages
       - name: Run Lint
         run: yarn lint
