name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: publish-${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: "package.json"
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --immutable
      - name: Creating .yarnrc
        run: |
          cat << EOF > "$HOME/.yarnrc"
              npmAlwaysAuth: true
              npmPublishRegistry: "https://registry.npmjs.org"
              npmAuthToken: $NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(repo): version packages"
          title: "chore(repo): version packages"
          version: yarn changeset version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.KNOCK_ENG_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
