name: Setup Files

on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: setup-files-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: "package.json"
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --immutable
      - name: Cache Build
        id: build-packages-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            **/dist
          key: build:packages-${{ hashFiles('packages') }}
      - name: Build Packages
        if: steps.build-packages-cache.outputs.cache-hit != 'true'
        run: yarn build:packages
