name: Unit Test Packages

on:
  workflow_call:

concurrency:
  group: unit-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
   unit-test-packages:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
          node-version-file: "package.json"
          cache: 'yarn'
       - name: Cache Build
         id: build-packages-cache
         uses: actions/cache@v3
         with:
           path: |
             **/dist
           key: build:packages-${{ hashFiles('packages') }}
       - name: Install Dependencies
         run: yarn --frozen-lockfile --prefer-offline
       - name: Build Packages
         if: steps.build-packages-cache.outputs.cache-hit != 'true'
         run: yarn build:packages
       - name: Run Tests
         run: yarn test
       # TODO: Collect Coverage and display in repo

